server:
  servlet:
    context-path: /chattyai
  tomcat:
    connection-timeout: 10m
spring:
  profiles:
    active: cn
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    async:
      request-timeout: 10m
logging:
  config: classpath:log4j2.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true

openai:
  defaultSystemPrompt: You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown. 不回答任何政治相关问题
  baseUrl: http://52.15.253.100:38820
  model: gpt-3.5-turbo
  timeoutSeconds: 600